# Exercício:

## 1 – Um objeto composto multidimensional (matriz) pode receber  objeto composto unidimensional (vetor)?

In [1]:
matriz = [['a', 'b', 'c'], [1, 2, 3]]

matriz

[['a', 'b', 'c'], [1, 2, 3]]

R: Sim.

## 2 – No exercício 9 da última aula, foram instanciadas 5 listas. Instancie um objeto composto multidimensional da classe lista com estes cinco vetores. Recupere a matriz.

In [3]:
# Listas instanciadas no ex 9 da ultima aula:
lista_de_genes = ["oxa23", "kpc", "vim", "ndm", "tet"]
oxa_23 = [len(lista_de_genes[0]), lista_de_genes[0][0:2], lista_de_genes[0].count("a"), 'hu' in lista_de_genes[0]]
kpc = [len(lista_de_genes[1]), lista_de_genes[1][0:2], lista_de_genes[1].count("a"), 'hu' in lista_de_genes[1]]
vim = [len(lista_de_genes[2]), lista_de_genes[2][0:2], lista_de_genes[2].count("a"), 'hu' in lista_de_genes[2]]
ndm = [len(lista_de_genes[3]), lista_de_genes[3][0:2], lista_de_genes[3].count("a"), 'hu' in lista_de_genes[3]]
tet = [len(lista_de_genes[4]), lista_de_genes[4][0:2], lista_de_genes[4].count("a"), 'hu' in lista_de_genes[4]]

In [4]:
obj_c_multi = [oxa_23, kpc, vim, ndm, tet]

obj_c_multi

[[5, 'ox', 1, False],
 [3, 'kp', 0, False],
 [3, 'vi', 0, False],
 [3, 'nd', 0, False],
 [3, 'te', 0, False]]

## 3 – Copie e converta o objeto instanciado no exercício 2 para um NumPy array. Recupere o array.

In [5]:
import numpy as np

array = np.array(obj_c_multi)

array

array([['5', 'ox', '1', 'False'],
       ['3', 'kp', '0', 'False'],
       ['3', 'vi', '0', 'False'],
       ['3', 'nd', '0', 'False'],
       ['3', 'te', '0', 'False']], dtype='<U21')

## 4 – Recupere todos os itens do terceiro gene.

In [6]:
array[2]

array(['3', 'vi', '0', 'False'], dtype='<U21')

## 5 – Verifique se todos os nomes dos genes tem ou não os caracteres 'hu'.

In [7]:
array[:,-1]

array(['False', 'False', 'False', 'False', 'False'], dtype='<U21')

## 6 – Recupere do segundo e quarto genes, os dois primeiros caracteres dos nomes e os quantitativos de 'a' presentes nos nomes dos genes.

In [25]:
array[[1,3], 1:3]

array([['kp', '0'],
       ['nd', '0']], dtype='<U21')

## 7 – Converta o objeto instanciado no exercício 10 da aula anterior para uma DataFrame Pandas. Nesta DataFrame, os index devem ser os nomes dos genes e cada coluna deve ter um nome que indique seu conteúdo. Recupere a DataFrame.

In [27]:
# Objeto instanciado no ex 10:
gene_dict = {
    'oxa23': [5, 'ox', 1, False],
    'kpc': [3, 'kp', 0, False],
    'vim': [3, 'vi', 0, False],
    'ndm': [3, 'nd', 0, False],
    'tet': [3, 'te', 0, False]}

In [28]:
import pandas as pd

In [41]:
df = pd.DataFrame(gene_dict).T
                  
df.columns = ['len', 'inicio_nome', 'count_a', 'hu_in_name']

df

      len inicio_nome count_a hu_in_name
oxa23   5          ox       1      False
kpc     3          kp       0      False
vim     3          vi       0      False
ndm     3          nd       0      False
tet     3          te       0      False

## 8 – Da DataFrame do exercício anterior recupere os números de caracteres e quantas vezes aparece o caractere ‘a’ de todos os genes.

In [48]:
df[['len', 'count_a']]

      len count_a
oxa23   5       1
kpc     3       0
vim     3       0
ndm     3       0
tet     3       0

## 9 – Da DataFrame do exercício anterior recupere se no nome aparecem os caracteres ‘hu’, para o primeiro e o terceiro genes.

In [54]:
df.iloc[[0,2]]['hu_in_name']

oxa23    False
vim      False
Name: hu_in_name, dtype: object

## 10 – Importe o data.csv (dados de seguro na Flórida em 2012) para uma DataFrame. Armazene em um dicionário o número de entradas, uma lista com as classes das colunas e outra lista com o número de elementos de cada classe, três listas, contendo a média, o desvio padrão e o terceiro quartil da primeira, quarta e nona colunas . Recupere o dicionário.

In [73]:
florida = pd.read_csv('../data/data.csv')
florida.head()

,policyID,statecode,county,eq_site_limit,hu_site_limit,fl_site_limit,fr_site_limit,tiv_2011,tiv_2012,eq_site_deductible,hu_site_deductible,fl_site_deductible,fr_site_deductible,point_latitude,point_longitude,line,construction,point_granularity
0,119736,FL,CLAY COUNTY,498960.0,498960.00,498960.0,498960.0,498960.00,792148.90,0.0,9979.2,0.0,0,30.102261,-81.711777,Residential,Masonry,1
1,448094,FL,CLAY COUNTY,1322376.3,1322376.30,1322376.3,1322376.3,1322376.30,1438163.57,0.0,0.0,0.0,0,30.063936,-81.707664,Residential,Masonry,3
2,206893,FL,CLAY COUNTY,190724.4,190724.40,190724.4,190724.4,190724.40,192476.78,0.0,0.0,0.0,0,30.089579,-81.700455,Residential,Wood,1
3,333743,FL,CLAY COUNTY,0.0,79520.76,0.0,0.0,79520.76,86854.48,0.0,0.0,0.0,0,30.063236,-81.707703,Residential,Wood,3
4,172534,FL,CLAY COUNTY,0.0,254281.50,0.0,254281.5,254281.50,246144.49,0.0,0.0,0.0,0,30.060614,-81.702675,Residential,Wood,1

In [119]:
linhas = florida.shape[0]

In [106]:
classes_colunas = list(florida.dtypes)

In [96]:
#florida.dtypes.value_counts()
n_elementos_classes = florida.dtypes.value_counts().to_list()
n_elementos_classes

[11, 4, 3]

In [112]:
florida_stats = florida[['policyID', 'eq_site_limit', 'tiv_2012']].describe()

florida_stats

            policyID  eq_site_limit      tiv_2012
count   36634.000000   3.663400e+04  3.663400e+04
mean   548661.937189   7.314780e+05  2.571004e+06
std    259912.926494   1.752300e+07  2.036777e+07
min    100074.000000   0.000000e+00  7.337000e+01
25%    323647.750000   0.000000e+00  5.401351e+04
50%    548525.000000   0.000000e+00  2.416310e+05
75%    774252.000000   0.000000e+00  1.128871e+06
max    999971.000000   2.160000e+09  1.701000e+09

In [117]:
mean = florida_stats.loc['mean'].to_list()
std = florida_stats.loc['std'].to_list()
terceiro_quartil = florida_stats.loc['75%'].to_list()

print(mean)
print(std)
print(terceiro_quartil)

[548661.9371894961, 731478.0068460993, 2571004.0973420865]
[259912.9264939009, 17523003.588415083, 20367766.569178067]
[774252.0, 0.0, 1128871.1824999999]

In [115]:
std = florida_stats.loc['std'].to_list()
std

[259912.9264939009, 17523003.588415083, 20367766.569178067]

In [121]:
dict_florida = {
    'n_entradas': linhas,
    'classes_colunas': classes_colunas,
    'n_elementos_classes': n_elementos_classes,
    'media': mean,
    'desv': std,
    'terceiro_quartil': terceiro_quartil,
    }

dict_florida

{'n_entradas': 36634,
 'classes_colunas': [dtype('int64'),
  <StringDtype(storage='python', na_value=nan)>,
  <StringDtype(storage='python', na_value=nan)>,
  dtype('float64'),
  dtype('float64'),
  dtype('float64'),
  dtype('float64'),
  dtype('float64'),
  dtype('float64'),
  dtype('float64'),
  dtype('float64'),
  dtype('float64'),
  dtype('int64'),
  dtype('float64'),
  dtype('float64'),
  <StringDtype(storage='python', na_value=nan)>,
  <StringDtype(storage='python', na_value=nan)>,
  dtype('int64')],
 'n_elementos_classes': [11, 4, 3],
 'media': [548661.9371894961, 731478.0068460993, 2571004.0973420865],
 'desv': [259912.9264939009, 17523003.588415083, 20367766.569178067],
 'terceiro_quartil': [774252.0, 0.0, 1128871.1824999999]}