# Exercício:

## 01 – Obtenha os resultados e retorne o código Python dos seguintes cálculos:

<br>a = 2.0 + 3.0 / 5.0 == 10
<br>b = (a + 10.2) - 5.0 * 2.0 <= 2.9
<br>c = 10 <= a / b + 33.8 < 100
<br>d = 5 != a / (b + c)
<br>e = 33 == d * 2

In [4]:
a = 2.0 + 3.0 / 5.0 == 10
b = (a + 10.2) - 5.0 * 2.0 <= 2.9
c = 10 <= a / b + 33.8 < 100
d = 5 != a / (b + c)
e = 33 == d * 2

print(f"a = {a}")
print(f"b = {b}")
print(f"c = {c}")
print(f"d = {d}")
print(f"e = {e}")

a = False
b = True
c = True
d = True
e = False

## 02 – Altere os operadores relacionais para modificar o resultado de cada uma das comparações.

<br>('a',1,True,'b',0,False) != ('a',True,1,'b',False,0)
<br>['a',1,True,'b',0,False] != ('a',True,1,'b',False,0)
<br>['a',1,True,'b',0,False] != ['a',True,1,'b',False,0]
<br>['a',1,True,'b',0,False] > ['a',True,1]
<br>['a',1,True,'b',0,False] == 1
<br>['a',True,1] <= ['a',True,1] < ['a',1,True,'b',0,False]

In [12]:
('a',1,True,'b',0,False) == ('a',True,1,'b',False,0)

True

In [13]:
['a',1,True,'b',0,False] == ('a',True,1,'b',False,0)

False

In [14]:
['a',1,True,'b',0,False] < ['a',True,1]

False

In [15]:
['a',1,True,'b',0,False] != 1

True

In [16]:
['a',True,1] <= ['a',True,1] > ['a',1,True,'b',0,False]

False

## 03 – Usando o método DataFrame.to_csv(‘nome_do_arquivo.csv’) exporte o objeto obtido no exercício 10 da aula anterior para um arquivo CSV. Usando o método pd.read_csv(‘nome_do_arquivo.csv’) instancie uma DataFrame. Use o valor ‘Unnamed: 0’ no parâmetro index_col, para ajustar o index. Arredonde os valores para até três casas decimais, usando o método round().
Recupere a DataFrame.

In [ ]:
import pandas as pd

df = pd.read_csv("df_aula_7.csv", index_col=0) # em vez de 'Unnamed: 0' usei apenas 0 com esse parametro
df

                    0      1       2      3  media_linhas
0               2.600  2.800  34.729  0.069      10.04950
1               0.139  1.612   1.673  5.893       2.32925
2               0.263  0.372   2.600  2.800       1.50875
3              34.729  0.069   0.139  1.612       9.13725
4               1.673  5.893   0.263  0.372       2.05025
media_colunas   7.881  2.149   7.881  2.149       5.01500

In [23]:
df = df.round(3)
df

                    0      1       2      3  media_linhas
0               2.600  2.800  34.729  0.069        10.050
1               0.139  1.612   1.673  5.893         2.329
2               0.263  0.372   2.600  2.800         1.509
3              34.729  0.069   0.139  1.612         9.137
4               1.673  5.893   0.263  0.372         2.050
media_colunas   7.881  2.149   7.881  2.149         5.015

## 04 – Instancie um numpy array que apresente o mesmo formato (linhas e colunas) da DataFrame. Este array deve conter apenas inteiros uns.
Recupere o array.

Obs.: Procure na internet o método numpy.ones()

In [37]:
import numpy as np
 
shape_do_df = df.shape
shape_do_df

(6, 5)

In [40]:
array_ones = np.ones(shape_do_df)
array_ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

## 05 – Quantos dos valores contidos na DataFrame são iguais aos valores no array?

In [42]:
array_df = np.array(df)
array_df

array([[ 2.6  ,  2.8  , 34.729,  0.069, 10.05 ],
       [ 0.139,  1.612,  1.673,  5.893,  2.329],
       [ 0.263,  0.372,  2.6  ,  2.8  ,  1.509],
       [34.729,  0.069,  0.139,  1.612,  9.137],
       [ 1.673,  5.893,  0.263,  0.372,  2.05 ],
       [ 7.881,  2.149,  7.881,  2.149,  5.015]])

In [ ]:
array_bool = array_df == array_ones
array_bool

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [53]:
np.sum(array_bool) #pq 0 e False e 1 é True

np.int64(0)

## 06 – Quantos dos valores contidos na DataFrame são superiores aos valores no array?

In [52]:
np.sum(array_df > array_ones)

np.int64(22)

## 07 – Quantos dos valores contidos na DataFrame são iguais ou inferiores aos valores no array?

In [54]:
np.sum(array_df <= array_ones)

np.int64(8)

## 08 – Quantos dos valores contidos na DataFrame estão entre 0 e 1?

In [67]:
np.sum((array_df <= 1) & (array_df >= 0))

np.int64(8)

## 09 – Quantos dos valores das médias das linhas são inferiores ou iguais à 5?

Obs 1.: Usando o método de classe, você pode converter qualquer objeto em outra classe. Ex. obj = list(array)

Obs 2.: Assim com o objeto da classe str, listas também possuem a função count()

In [80]:
lista = list(array_df[:,-1] <= 5)
lista

lista.count(True)

3

## 10 – Quantos dos valores das médias das colunas são superiores à 5?

In [87]:
lista_2 = list(array_df[-1,:] > 5 )

# Aqui eu peguei só as coluna 0:4 pq a coluna 5 não tem a 

lista_2.count(True)

3